name: Deploy to AWS EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          cat <<EOF > config.env
          APP_PORT=${{ secrets.APP_PORT }}
          DB_HOST=${{ secrets.BDD_HOST }}
          DB_PORT=${{ secrets.BDD_PORT }}
          DB_USER=${{ secrets.BDD_USER }}
          DB_PASSWORD=${{ secrets.BDD_PASSWORD }}
          DB_DATABASE=${{ secrets.BDD_DATABASE }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
          EOF
        
      - name: Transfer config.env file via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "config.env"
          target: "/home/ec2-user/ntropresupuesto/ntropresupuesto-api/config/"

      - name: Create .cors file
        run: |
          cat <<EOF > cors.js
          ${{ secrets.CORS }}
          EOF

      - name: Transfer .cors file via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "cors.js"
          target: "/home/ec2-user/ntropresupuesto/ntropresupuesto-api/config/"

      - name: EC2 deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/ntropresupuesto/ntropresupuesto-api
            export NODE_OPTIONS=--max-old-space-size=4096
            gh repo sync
            npm install
            pm2 restart 1
