name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
      name: Lint JavaScript Files
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install and Run Linter
        run: |
          # This command finds all JavaScript files recursively and runs JSHint on them
          npm init -y
          npm install eslint-config-standard eslint-plugin-import eslint-plugin-n eslint-plugin-promise
          find ./ -type f -name app.js -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          find ./src -type f -name "*.js" -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          find ./config -type f -name "*.js" -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          echo "Linted all the js files successfully"
